apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment-v2
  labels:
    app: employees-v2
  namespace: app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees-v2
  template:
    metadata:
      labels:
        app: employees-v2
    spec:
      containers:
      - name: application-container
        image: 937274605158.dkr.ecr.us-east-1.amazonaws.com/application:latest-v2
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: 10.96.81.176
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DBPORT
          value: "3306"
        - name: APP_COLOR
          value: "green"
        - name: DATABASE
          value: "employees"
      imagePullSecrets:
      - name: regcred
