apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-namespace
  labels:
    app: mysql
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 937274605158.dkr.ecr.us-east-1.amazonaws.com/database:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pw
          ports:
            - containerPort: 3306
      imagePullSecrets:
          - name: regcred
